Repository codestates-seb/seb40_main_025, pull requests merged in 2022-11, with the labels that each got.

#7 [BE] member, gallery, vote 엔티티 맵핑
  .github/ISSUE_TEMPLATE/issue-task-card.md
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/Gallery.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/GalleryStatus.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/vote/entity/Vote.java
  server/oneyearfourcut/src/main/resources/application.yml
Labels: BE, Feat

#11 [BE-Feat/#6,#10] Comment Entity 및 Controller(Mock Data) 구현
  server/oneyearfourcut/build.gradle
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtWorkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/ArtWorkCommentListResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/ArtWorkCommentResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/CommentRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/GalleryCommentListResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/GalleryCommentResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Reply.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/repository/CommentRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/Gallery.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/MemberController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/service/MemberService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/page/PageInfo.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/page/PageResponseDto.java
Labels: BE, Feat, Style

#13 [BE/#11] Comment Controller 수정
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/Gallery.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
Labels: BE, Fix

#16 chore/프론트엔드 초기셋팅
  client/.gitignore
  client/.prettierrc.json
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/ExampleFoler/Login.js
  client/src/ExampleFoler/api.js
  client/src/ExampleFoler/components/LoginSidebar/LoginTemplet.js
  client/src/ExampleFoler/components/LoginSidebar/index.js
  client/src/index.css
  client/src/index.tsx
  client/src/shared/styled/GlobalStyled.js
  client/src/shared/styled/Theme.js
  client/tsconfig.json
Labels: FE, Chore

#15 [Feat] ArtWork Entity 연관 관계 매핑 및 Alarm - Member매핑
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/ArtWork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/vote/entity/Vote.java
Labels: BE, Feat

#18 chore/프론트엔드 초기셋팅2
  client/.gitignore
  client/src/ExampleFoler/.gitkeep
  client/src/ExampleFoler/components/.gitkeep
  client/src/ExampleFoler/hooks/.gitkeep
  client/src/assets/.gitkeep
  client/src/hooks/.gitkeep
  client/src/shared/components/.gitkeep
  client/src/shared/components/Buttons/.gitkeep
  client/src/shared/components/Icons/.gitkeep
  client/src/shared/components/Input/.gitkeep
  client/src/shared/components/Modal/.gitkeep
  client/src/shared/hooks/.gitkeep
  client/src/shared/libs/.gitkeep
  client/src/shared/store/.gitkeep
  client/src/shared/styled/.gitkeep
  client/src/shared/utils/.gitkeep
  client/src/store/.gitkeep
Labels: FE, Chore

#21 [Feat] 작품 수정 API (Mock Data) 추가, 작품 응답 데이터 memberId 추가
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtWorkController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtWorkResponseDto.java
Labels: BE, Feat

#22 [Feat] data.sql 추가
  server/oneyearfourcut/src/main/resources/application.yml
  server/oneyearfourcut/src/main/resources/db/data.sql
Labels: BE, Feat

#24 [Feat/#9] 긴급 PR
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/ArtWorkCommentResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/GalleryCommentResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
Labels: BE, Feat, Fix, Style

#32 🔨CHORE: 절대 경로 지정
  client/tsconfig.json
Labels: FE, Chore

#30 Theme provider, Global Style 적용
  client/.gitmessage.txt
  client/public/index.html
  client/src/index.tsx
  client/src/shared/styled/GlobalStyle.tsx
  client/src/shared/styled/GlobalStyled.js
  client/src/shared/styled/Theme.js
  client/src/shared/styled/Theme.ts
  client/src/shared/styled/styled.d.ts
Labels: FE, Feat

#36 [BE] CommentService CRUD, Mapper 미완성
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
Labels: BE, Feat, Fix, Style

#33 [BE] Member, Gallery, Vote Controller Mock객체 반환 구현, 관련 dto 구현
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/dto/GalleryRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/dto/GalleryResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/dto/MemberRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/vote/controller/VoteController.java
  server/oneyearfourcut/src/main/resources/db/data.sql
Labels: BE, Feat

#34 [BE] ArtworkService - create 구현
  .DS_Store
  server/oneyearfourcut/src/main/generated/com/codestates/mainproject/oneyearfourcut/domain/artwork/mapper/ArtworkMapperImpl.java
  server/oneyearfourcut/src/main/generated/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapperImpl.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/mapper/ArtworkMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/repository/ArtworkRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/Gallery.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
  server/oneyearfourcut/src/main/resources/db/data.sql
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/artwork/repository/ArtworkRepositoryTest.java
Labels: BE, Feat

#40 🔨CHORE: polished 패키지 설치, 라우팅용 Pagaes 폴더 추가
  client/package-lock.json
  client/package.json
  client/src/Pages/.gitkeep
Labels: FE, Chore

#41 [BE] Member controller 로직 구현, Mapper 추가
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/mapper/MemberMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/service/MemberService.java
Labels: BE, Feat

#44 [BE] postGallery 구현
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/Gallery.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/mapper/GalleryMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/auditable/Auditable.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryServiceMockTest.java
Labels: BE, Feat

#48 [Feat] ArtworkService 작품 전체 조회 로직 구현
  server/oneyearfourcut/gradlew
  server/oneyearfourcut/src/main/generated/com/codestates/mainproject/oneyearfourcut/domain/artwork/mapper/ArtworkMapperImpl.java
  server/oneyearfourcut/src/main/generated/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapperImpl.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkListResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/mapper/ArtworkMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/repository/ArtworkRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/resources/db/data.sql
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/artwork/repository/ArtworkRepositoryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/repository/ArtworkRepositoryTest.java
Labels: BE, Feat

#45 [BE/#39] Comment Mapper 구현 완료
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/ArtworkCommentListResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/ArtworkCommentResponse.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/CommentRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/GalleryCommentListResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/GalleryCommentResponse.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/ReplyRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/ReplyResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/ReplyMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/repository/CommentRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/Gallery.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberController.java
  server/oneyearfourcut/src/main/resources/db/data.sql
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/Comment/CommentMapperTest.java
Labels: BE, Feat, Style, Test

#52 [Feat] 개별 작품 조회 비지니스 로직 구현
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/mapper/ArtworkMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/repository/ArtworkRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/Gallery.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
  server/oneyearfourcut/src/main/resources/db/data.sql
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/repository/ArtworkRepositoryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapperTest.java
Labels: BE, Feat

#62 Fe 12/headermockup - 헤더구현, 등록페이지 구현, 모달창구현
  client/src/App.tsx
  client/src/UploadPicture/components/Container.tsx
  client/src/UploadPicture/components/Input.tsx
  client/src/UploadPicture/components/SvgComponents.tsx
  client/src/UploadPicture/components/Upload.tsx
  client/src/UploadPicture/index.tsx
  client/src/index.css
  client/src/shared/components/.gitkeep
  client/src/shared/components/Header/components/HeaderBox.tsx
  client/src/shared/components/Header/components/HeaderButtons.tsx
  client/src/shared/components/Header/index.tsx
  client/src/shared/components/Modal/.gitkeep
  client/src/shared/components/Modal/components/Alert.tsx
  client/src/shared/components/Modal/components/ModalContainer.ts
  client/src/shared/components/Modal/components/SvgComponents.tsx
  client/src/shared/styled/GlobalStyle.tsx
  client/src/shared/styled/Theme.ts
  client/src/store/.gitkeep
  client/src/store/store.ts
Labels: FE, Feat, Style

#57 [Feat] 작품 수정 비지니스 로직 구현
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
Labels: BE, Feat, Style, Refactor

#58 [BE] Gallery controller, service 구현
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/Gallery.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/CreateGalleryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/FindGalleryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryServiceMockTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/ModifyGalleryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/VerifiedGalleryExistTest.java
Labels: BE, Feat

#65 [FE] 전시관 모아보기 페이지 - 전체보기
  client/public/images/5.jpg
  client/public/images/6.jpg
  client/src/Gallery/GalleryAllPic.tsx
  client/src/Gallery/GalleryFourPic.tsx
  client/src/Gallery/components/DynamicGallery/index.tsx
  client/src/Gallery/components/DynamicGallery/style.tsx
  client/src/Gallery/components/FilterBox/index.tsx
  client/src/Gallery/components/FilterBox/style.tsx
  client/src/Gallery/components/GalleryInfo/style.tsx
  client/src/assets/Icon/filter.tsx
  client/src/shared/components/Buttons/index.tsx
Labels: FE, Feat, Style

#64 [BE] Comment CRUD 및 Pagination 기능구현 완료
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/ReplyController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/CommentStatus.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/CommentType.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Reply.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/repository/CommentRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/repository/ReplyRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/ReplyService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
  server/oneyearfourcut/src/main/resources/application.yml
  server/oneyearfourcut/src/main/resources/db/data.sql
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentServiceTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/ReplyServiceTest.java
Labels: BE, Feat, Refactor

#66 [BE/#53] 작품 삭제 및 올해 네컷 구현
  .DS_Store
  server/.DS_Store
  server/oneyearfourcut/.DS_Store
  server/oneyearfourcut/src/.DS_Store
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/repository/ArtworkRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/resources/db/data.sql
Labels: BE, Feat, Refactor

#70 Style/fe 63 profile style
  client/src/AlarmList/components/Alarm.tsx
  client/src/AlarmList/components/AlarmContainer.ts
  client/src/AlarmList/components/Filter.tsx
  client/src/AlarmList/components/FilterContainer.ts
  client/src/AlarmList/index.tsx
  client/src/UploadPicture/index.tsx
  client/src/shared/components/Header/components/HeaderButtons.tsx
  client/src/shared/components/Modal/components/Alert.tsx
  client/src/shared/components/Modal/components/ModalBackdrop.tsx
  client/src/shared/components/Modal/components/ModalContainer.ts
  client/src/shared/components/Modal/components/Profile.tsx
  client/src/shared/components/Modal/components/SvgComponents.tsx
  client/src/shared/styled/.gitkeep
  client/src/shared/styled/Theme.ts
  client/src/store/store.ts
Labels: FE, Feat, Style

#71 [FE #05] 싱글 페이지 덧글 창 보기 구현
  client/src/Single Comments/CommentInput.tsx
  client/src/Single Comments/CommentsZone.tsx
  client/src/Single Comments/Single Comment/SingleComment.tsx
  client/src/Single Comments/Single Comment/sampledata.ts
  client/src/Single Comments/Single Comments.style.tsx
  client/src/Single Comments/index.tsx
Labels: FE, Feat, Style

#76 [FE #10 #11 #12] 404, 갤러리 및 덧글 삭제 페이지 구현
  client/src/Delete/Delete.style.tsx
  client/src/Delete/DeleteGallery.tsx
  client/src/Delete/DeleteUser.tsx
  client/src/ForBidden/ForBidden.style.tsx
  client/src/ForBidden/index.tsx
  client/src/SingleComments/CommentInput.tsx
  client/src/SingleComments/CommentsZone.tsx
  client/src/SingleComments/Single Comments.style.tsx
  client/src/SingleComments/SingleComment/SingleComment.tsx
  client/src/SingleComments/SingleComment/sampledata.ts
  client/src/SingleComments/index.tsx
  client/src/Singlepictures/Single picture.jsx
  client/src/Singlepictures/index.tsx
  client/src/Singlepictures/ts-practice/singlepage.style.tsx
  client/src/shared/components/Buttons/index.tsx
  client/src/shared/components/Icons/ForbiddenIcon.tsx
Labels: FE, Style

#75 Feat/fe 72 toast message
  client/src/AlarmList/components/Filter.tsx
  client/src/AlarmList/index.tsx
  client/src/App.tsx
  client/src/UploadPicture/components/Container.tsx
  client/src/UploadPicture/index.tsx
  client/src/index.css
  client/src/shared/components/Header/components/HeaderBox.tsx
  client/src/shared/components/Header/components/HeaderButtons.tsx
  client/src/shared/components/Header/index.tsx
  client/src/shared/components/Modal/components/Alert.tsx
  client/src/shared/components/Modal/components/ModalBackdrop.tsx
  client/src/shared/components/Modal/components/ModalContainer.ts
  client/src/shared/components/Toast/components/SvgComponents.tsx
  client/src/shared/components/Toast/components/ToastContainer.tsx
  client/src/shared/components/Toast/components/ToastMessage.tsx
  client/src/shared/components/Toast/index.tsx
  client/src/shared/styled/Theme.ts
  client/src/store/store.ts
Labels: FE, Feat, Style

#73 [Feat/#69] 좋아요 기능 구현
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkListResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/OneYearFourCutResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/vote/controller/VoteController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/vote/entity/Vote.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/vote/repository/VoteRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/vote/service/VoteService.java
  server/oneyearfourcut/src/main/resources/db/data.sql
Labels: BE, Feat, Refactor

#80 ✨FEAT : react-router-dom 설정
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Single Comments/CommentInput.tsx
  client/src/Single Comments/CommentsZone.tsx
  client/src/Single Comments/Single Comment/SingleComment.tsx
  client/src/Single Comments/Single Comment/sampledata.ts
  client/src/Single Comments/Single Comments.style.tsx
  client/src/Single Comments/index.tsx
  client/src/SingleComments/CommentsZone.tsx
  client/src/SingleComments/index.tsx
  client/src/UploadPicture/api.ts
  client/src/shared/components/Header/components/HeaderBox.tsx
  client/src/shared/components/Header/components/HeaderButtons.tsx
  client/src/shared/components/Header/index.tsx
  client/src/shared/utils/.gitkeep
  client/src/shared/utils/axios.ts
Labels: FE, Feat

#82 [FE] 메인 페이지 및 전시관 설정 페이지 구현
  client/public/images/kakao_login_large.png
  client/public/images/kakao_login_large_narrow.png
  client/public/images/kakao_login_large_wide.png
  client/public/images/kakao_login_medium.png
  client/public/images/kakao_login_medium_narrow.png
  client/public/images/kakao_login_medium_wide.png
  client/public/images/kakao_login_small.png
  client/src/Gallery/GalleryAllPic.tsx
  client/src/Gallery/GalleryFourPic.tsx
  client/src/GallerySetting/GallerySetting.tsx
  client/src/GallerySetting/components/Input/index.tsx
  client/src/GallerySetting/components/Input/style.tsx
  client/src/Intro/Intro.tsx
  client/src/Intro/components/Envelope/index.tsx
  client/src/Intro/components/Envelope/style.tsx
  client/src/Intro/components/Kakao/index.tsx
  client/src/Intro/components/Kakao/style.tsx
  client/src/Intro/components/Letter/index.tsx
  client/src/Intro/components/Letter/style.tsx
  client/src/Intro/components/Scroll/index.tsx
  client/src/Intro/components/Scroll/style.tsx
  client/src/shared/components/Buttons/index.tsx
  client/src/shared/styled/Theme.ts
Labels: FE, Feat, Style

#77 [Feat] Oauth2.0 카카오 로그인, JWT 구현
  server/oneyearfourcut/.gitignore
  server/oneyearfourcut/build.gradle
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/JWTController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Role.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/repository/MemberRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/service/MemberService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/WebConfig.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/LoginMember.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/LoginMemberArgumentResolver.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/SecurityConfig.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/ThirdOAuth2Provider.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/filter/JwtVerificationFilter.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/handler/ErrorResponder.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/handler/MemberAuthenticationEntryPoint.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/handler/OAuth2MemberSuccessHandler.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/jwt/JwtTokenizer.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/dto/ErrorResponse.java
  server/oneyearfourcut/src/main/resources/application.yml
  server/oneyearfourcut/src/main/resources/templates/index.html
  server/oneyearfourcut/src/main/resources/templates/receive-token.html
Labels: BE, Feat

#81 [Feat] Reply CRUD 기능 구현
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/OneyearfourcutApplication.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/ReplyController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/CommentArtworkResDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/CommentGalleryResDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/CommentReqDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/ReplyResDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/ReplyResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/CommentStatus.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Reply.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/ReplyMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/repository/CommentRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/repository/ReplyRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/ReplyService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/page/ArtworkPageResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/page/GalleryPageResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/page/ReplyListResponseDto.java
  server/oneyearfourcut/src/main/resources/db/data.sql
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapperTest.java
Labels: BE, Feat, Refactor

#88 [BE] Member, Gallery 도메인 리팩터링
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/dto/GalleryRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/Gallery.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/mapper/GalleryMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/dto/MemberRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/dto/MemberResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/MemberStatus.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/mapper/MemberMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/service/MemberService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/handler/OAuth2MemberSuccessHandler.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
  server/oneyearfourcut/src/main/resources/db/data.sql
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/CreateGalleryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/DeleteGalleryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/FindGalleryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/ModifyGalleryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/VerifiedGalleryExistTest.java
Labels: BE, Refactor

#89 [BE/#74] Artwork, ArtworkLike 관련 리팩토링
  .DS_Store
  server/oneyearfourcut/src/main/.DS_Store
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/controller/ArtworkLikeController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/entity/ArtworkLike.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/repository/ArtworkLikeRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/service/ArtworkLikeService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkListResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/OneYearFourCutResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/ArtworkStatus.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/mapper/ArtworkMapper.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/repository/ArtworkRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/vote/controller/VoteController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
  server/oneyearfourcut/src/main/resources/db/data.sql
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/repository/ArtworkRepositoryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkServiceLocalTest.java
Labels: BE, Feat, Refactor

#95 Feat/fe 84 업로드 페이지 기능 구현
  client/src/UploadPicture/api.ts
  client/src/UploadPicture/components/Container.tsx
  client/src/UploadPicture/components/Input.tsx
  client/src/UploadPicture/components/SvgComponents.tsx
  client/src/UploadPicture/components/Upload.tsx
  client/src/UploadPicture/components/UploadImg.tsx
  client/src/UploadPicture/hook/useUpload.tsx
  client/src/UploadPicture/index.tsx
  client/src/UploadPicture/types.ts
  client/src/index.tsx
  client/src/shared/components/Modal/AlertData.ts
  client/src/shared/components/Modal/components/Alert.tsx
  client/src/shared/components/Toast/components/ToastContainer.tsx
  client/src/shared/components/Toast/components/ToastMessage.tsx
  client/src/shared/components/Toast/hooks/useToast.tsx
  client/src/shared/utils/axios.ts
  client/src/store/store.ts
  client/src/store/types.ts
  client/src/types.d.ts
Labels: FE, Feat, Style

#96 [BE] Member, Gallery api Rest Docs 작성
  .DS_Store
  server/.DS_Store
  server/oneyearfourcut/.DS_Store
  server/oneyearfourcut/.gitignore
  server/oneyearfourcut/build.gradle
  server/oneyearfourcut/src/.DS_Store
  server/oneyearfourcut/src/docs/asciidoc/index.adoc
  server/oneyearfourcut/src/main/.DS_Store
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/ReplyService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/dto/MemberRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/dto/MemberResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/service/MemberService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/LoginMemberArgumentResolver.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/filter/JwtVerificationFilter.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/handler/OAuth2MemberSuccessHandler.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/jwt/JwtTokenizer.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/jwt/PrincipalDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
  server/oneyearfourcut/src/main/resources/application-real.yml
  server/oneyearfourcut/src/main/resources/application.yml
  server/oneyearfourcut/src/main/resources/db/data.sql
  server/oneyearfourcut/src/main/resources/static/docs/index.html
  server/oneyearfourcut/src/main/resources/templates/index.html
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkServiceLocalTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/comment/repository/RepositoryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryControllerRestDocsTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/DeleteGalleryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/ModifyGalleryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberControllerRestDocsTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/global/util/ApiDocumentUtils.java
Labels: BE, Docs

#98 [BE/#90] RestDocs 구현 artwork, artworkLike
  server/oneyearfourcut/src/.DS_Store
  server/oneyearfourcut/src/docs/asciidocs/index.adoc
  server/oneyearfourcut/src/main/.DS_Store
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/controller/ArtworkLikeController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/entity/ArtworkLike.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/service/ArtworkLikeService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkServiceLocalTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/comment/repository/RepositoryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/like/controller/ArtworkLikeControllerTest.java
Labels: BE, Feat

#101 [BE/#100] AWS S3 이미지 업로드 구현
  server/oneyearfourcut/build.gradle
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/aws/config/S3Config.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/aws/service/AwsS3Service.java
  server/oneyearfourcut/src/main/resources/application.yml
Labels: BE, Feat

#103 [FE] 토큰 헤더에 담아 보내기
  client/.gitignore
  client/src/App.tsx
  client/src/Gallery/components/ButtonBox/index.tsx
  client/src/Gallery/components/FourCut/index.tsx
  client/src/GallerySetting/api.tsx
  client/src/GallerySetting/components/Input/index.tsx
  client/src/GallerySetting/galleryType.ts
  client/src/GallerySetting/hooks/useGalleryData.ts
  client/src/Intro/RedirectPage.tsx
  client/src/Intro/components/Kakao/index.tsx
  client/src/Intro/components/Kakao/style.tsx
  client/src/Intro/components/KakaoBtn/index.tsx
  client/src/Intro/components/KakaoBtn/style.tsx
  client/src/Intro/components/Scroll/index.tsx
  client/src/Intro/components/Scroll/style.tsx
  client/src/Intro/hooks/tokenStorage.ts
  client/src/shared/components/LinkButton/style.tsx
  client/src/shared/styled/Theme.ts
  client/src/shared/utils/axios.ts
Labels: FE, Feat, Style

#104 [BE] Gallery 수정, 삭제 url 수정
  server/oneyearfourcut/src/docs/asciidoc/index.adoc
  server/oneyearfourcut/src/docs/asciidocs/index.adoc
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/repository/GalleryRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/LoginMemberArgumentResolver.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
  server/oneyearfourcut/src/main/resources/static/docs/index.html
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryControllerRestDocsTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/DeleteGalleryTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/ModifyGalleryTest.java
Labels: BE, Fix

#110 ✨Fix : 전시관 관리 - 미적용 해결
  client/src/GallerySetting/GallerySetting.tsx
Labels: FE, Fix

#107 [Test/#86] Reply/Comment Rest Docs 및 Test 완료
  server/oneyearfourcut/src/docs/asciidoc/index.adoc
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/AlarmAction.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/AlarmType.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/proxy/Alarm.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/ReplyController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/CommentArtworkResDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/CommentGalleryResDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/ReplyResDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/ReplyService.java
  server/oneyearfourcut/src/main/resources/static/docs/index.html
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/AlarmControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/AlarmServiceTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkServiceLocalTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/ReplyControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/SampleTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/like/controller/ArtworkLikeControllerTest.java
Labels: BE, Feat, Docs, Test

#112 [BE/#102] Artwork, Like, Comment, Reply 유효성 검증 추가
  server/oneyearfourcut/build.gradle
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/controller/ArtworkLikeController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkPatchDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkPostDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/dto/CommentRequestDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/aws/service/AwsS3Service.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/LoginMemberArgumentResolver.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/handler/OAuth2MemberSuccessHandler.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/util/FileUtils.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/validator/NotSpace.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/validator/NotSpaceValidator.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkServiceLocalTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/like/controller/ArtworkLikeControllerTest.java
Labels: BE, Feat

#117 [BE] Member 수정, 조회 api 수정, Security 권한 설정
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/dto/MemberResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/service/MemberService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/SecurityConfig.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/handler/OAuth2MemberSuccessHandler.java
  server/oneyearfourcut/src/main/resources/static/docs/index.html
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/like/controller/ArtworkLikeControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberControllerRestDocsTest.java
Labels: BE, Feat

#118 [FE] 토큰, 유저 정보 저장
  client/src/Intro/RedirectPage.tsx
  client/src/Intro/api.ts
  client/src/Intro/hooks/useUserData.ts
  client/src/shared/components/Header/hook/useReceiveAlarm.tsx
  client/src/store/store.ts
  client/src/store/types.ts
Labels: FE, Feat

#121 Fe 111 gallarylink
  client/src/UploadPicture/index.tsx
  client/src/UploadPicture/types.ts
  client/src/shared/components/Header/components/HeaderButtons.tsx
  client/src/shared/components/Header/hook/useReceiveAlarm.tsx
  client/src/shared/components/Modal/components/ModalBackdrop.tsx
  client/src/shared/components/Modal/components/ModalContainer.ts
  client/src/shared/components/Modal/components/Profile.tsx
  client/src/shared/components/Modal/hook/useClipboardCopy.tsx
  client/src/shared/components/Toast/components/ToastContainer.tsx
Labels: FE, Feat

#123 전시관 api 수정
  client/src/Gallery/hooks/useLikeData.ts
  client/src/GallerySetting/GallerySetting.tsx
  client/src/GallerySetting/api.tsx
  client/src/GallerySetting/galleryType.ts
  client/src/Intro/RedirectPage.tsx
Labels: FE, Feat

#122 [FE] 서버 통신으로 갤러리 구현, 코멘트 구현 및 작성 가능
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/SingleComments/CommentInput.tsx
  client/src/SingleComments/CommentsZone.tsx
  client/src/SingleComments/Single Comments.style.tsx
  client/src/SingleComments/hooks/useCreateComment.tsx
  client/src/SingleComments/hooks/useDeleteComment.tsx
  client/src/SingleComments/hooks/useGetSingleComments.tsx
  client/src/SingleComments/index.tsx
  client/src/SinglePicture/SinglePicture.tsx
  client/src/SinglePicture/data/Sample.ts
  client/src/SinglePicture/index.tsx
  client/src/SinglePicture/styles.css
  client/src/SinglePicture/ts-practice/SinglePage.style.tsx
  client/src/Singlepictures/Single picture.jsx
  client/src/Singlepictures/index.tsx
  client/src/hooks/.gitkeep
  client/src/shared/components/Icons/XIcon.tsx
  client/src/shared/components/Icons/commentIcon.tsx
  client/src/shared/components/PicFooter/OpenComment.tsx
  client/src/shared/components/PicFooter/PicFooter.tsx
  client/src/shared/hooks/useDeleteSinglePic.tsx
  client/src/shared/hooks/useGetAllPost.tsx
Labels: FE, Feat

#125 FIX
  client/src/GallerySetting/GallerySetting.tsx
  client/src/SinglePicture/SinglePicture.tsx
Labels: FE, Fix

#126 [Feat/#116] 알림 기능 구현
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/service/ArtworkLikeService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/controller/AlarmController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/dto/AlarmReadCheckResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/dto/AlarmResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/proxy/AlarmAction.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/proxy/AlarmActionInterceptor.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/repository/AlarmRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/page/AlarmListDto.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/AlarmControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/AlarmServiceTest.java
Labels: BE, Feat

#130 [Fix/#129] 알림 에러수정
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/repository/AlarmRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
Labels: BE, Fix

#128 Feat/#119 re
  client/src/Gallery/components/GalleryInfo/index.tsx
  client/src/Gallery/hooks/useLikeData.ts
  client/src/GallerySetting/GallerySetting.tsx
  client/src/GallerySetting/api.tsx
  client/src/GallerySetting/hooks/useGalleryData.ts
  client/src/Intro/Redirect.tsx
  client/src/Intro/RedirectPage.tsx
  client/src/Intro/api.ts
Labels: FE, Feat, Refactor

#131 [Fix/#129] 알림 로직 및 에러 수정
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/controller/AlarmController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/repository/AlarmRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
Labels: BE, Fix

#135 [FE] 프로필 연동, 회원탈퇴, 로그아웃, 전시관삭제
  client/public/images/DefaultProfileImg.png
  client/public/index.html
  client/src/AlarmList/components/Alarm.tsx
  client/src/GallerySetting/GallerySetting.tsx
  client/src/Intro/api.ts
  client/src/UploadPicture/components/Container.tsx
  client/src/UploadPicture/components/Upload.tsx
  client/src/UploadPicture/components/UploadImg.tsx
  client/src/UploadPicture/index.tsx
  client/src/shared/components/Header/components/HeaderBox.tsx
  client/src/shared/components/Header/components/HeaderButtons.tsx
  client/src/shared/components/Header/index.tsx
  client/src/shared/components/Modal/Alert.tsx
  client/src/shared/components/Modal/AlertData.ts
  client/src/shared/components/Modal/Profile.tsx
  client/src/shared/components/Modal/components/ModalContainer.ts
  client/src/shared/components/Modal/components/Profile.tsx
  client/src/shared/components/Modal/hooks/useClipboardCopy.tsx
  client/src/shared/components/Modal/hooks/useHandleService.tsx
  client/src/shared/hooks/useNavigateSearch.tsx
  client/src/store/store.ts
  client/src/store/types.ts
Labels: FE, Feat

#137 [FE] 작품 사진 보이게 하기
  client/src/Gallery/GalleryFourPic.tsx
  client/src/Gallery/components/DynamicGallery/index.tsx
  client/src/Gallery/components/FourCut/index.tsx
  client/src/Gallery/components/FourCut/style.tsx
  client/src/Gallery/components/GalleryInfo/index.tsx
  client/src/Gallery/components/GalleryInfo/style.tsx
  client/src/GallerySetting/GallerySetting.tsx
Labels: FE, Feat

#138 [FE] 자잘한 기능 수정
  client/src/AlarmList/components/Alarm.tsx
  client/src/AlarmList/components/AlarmContainer.ts
  client/src/AlarmList/components/Filter.tsx
  client/src/AlarmList/hooks/useHandleIntersection.tsx
  client/src/AlarmList/types.ts
  client/src/Intro/api.ts
  client/src/shared/components/Header/hook/useReceiveAlarm.tsx
  client/src/shared/components/Modal/AlertData.ts
  client/src/shared/components/Modal/Profile.tsx
  client/src/shared/components/Modal/hooks/useClipboardCopy.tsx
  client/src/shared/components/Modal/hooks/useHandleService.tsx
  client/src/shared/hooks/useNavigateSearch.tsx
Labels: FE, Fix, Style
