Repository codestates-seb/seb40_main_025, pull requests merged in 2022-12, with the labels that each got.

#140 [FE #05] 좋아요, 개별 코멘트 삭제, 개별 게시글 삭제, 싱글 페이지 부르기 기능 추가
  client/src/SingleComments/CommentsZone.tsx
  client/src/SingleComments/SingleComment/SingleComment.style.tsx
  client/src/SingleComments/SingleComment/SingleComment.tsx
  client/src/SingleComments/SingleComment/sampledata.ts
  client/src/SingleComments/hooks/useDeleteComment.tsx
  client/src/SingleComments/index.tsx
  client/src/SinglePicture/SinglePicture.tsx
  client/src/SinglePicture/data/Sample.ts
  client/src/SinglePicture/hooks/useLikePictures.tsx
  client/src/SinglePicture/index.tsx
  client/src/shared/components/Buttons/likeButton.tsx
  client/src/shared/components/Icons/heartIcon.tsx
  client/src/shared/components/PicFooter/PicFooter.tsx
  client/src/shared/hooks/useDeleteSinglePic.tsx
  client/src/shared/hooks/useGetSinglePicture.tsx
Labels: FE, Feat, Style

#145 [FE] 전시관 관리 페이지 - 에러 해결, 라우팅
  client/src/App.tsx
  client/src/Gallery/GalleryAllPic.tsx
  client/src/Gallery/GalleryFourPic.tsx
  client/src/Gallery/components/BottonButton/index.tsx
  client/src/Gallery/components/BottonButton/style.tsx
  client/src/Gallery/components/DynamicGallery/index.tsx
  client/src/Gallery/components/FourCut/index.tsx
  client/src/Gallery/components/FourCut/style.tsx
  client/src/GallerySetting/components/Input/index.tsx
  client/src/GallerySetting/components/Input/style.tsx
  client/src/index.tsx
Labels: FE, Feat, Fix, Refactor

#147 [BE/#144] 알림 ID 및 빈 페이지 No content
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/dto/AlarmResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/ReplyService.java
Labels: BE, Fix

#148 [FE] 프로필 수정 기능, 토큰저장
  client/src/AlarmList/hooks/useHandleIntersection.tsx
  client/src/ExampleFoler/Login.js
  client/src/ExampleFoler/api.js
  client/src/ExampleFoler/components/.gitkeep
  client/src/ExampleFoler/components/LoginSidebar/LoginTemplet.js
  client/src/ExampleFoler/components/LoginSidebar/index.js
  client/src/ExampleFoler/hooks/.gitkeep
  client/src/Intro/RedirectPage.tsx
  client/src/UploadPicture/components/UploadImg.tsx
  client/src/UploadPicture/hook/useUpload.tsx
  client/src/UploadPicture/index.tsx
  client/src/shared/components/Header/hook/useReceiveAlarm.tsx
  client/src/shared/components/Modal/Profile.tsx
  client/src/shared/components/Modal/api.tsx
  client/src/shared/components/Modal/components/ModalContainer.ts
  client/src/shared/components/Modal/components/ProfileModify.tsx
  client/src/shared/components/Modal/hooks/useClipboardCopy.tsx
  client/src/shared/components/Modal/hooks/useHandleService.tsx
  client/src/shared/components/Modal/hooks/useModifyProfile.tsx
  client/src/shared/components/Modal/types.ts
  client/src/shared/components/Toast/ToastData.tsx
  client/src/shared/components/Toast/components/ToastContainer.tsx
  client/src/shared/components/Toast/hooks/useToast.tsx
  client/src/shared/libs/uploadHelper.ts
Labels: FE, Feat, Fix

#150 Feat/#146
  client/src/App.tsx
  client/src/Gallery/components/BottonButton/index.tsx
  client/src/Gallery/components/DynamicGallery/index.tsx
  client/src/Gallery/components/DynamicGallery/style.tsx
  client/src/Gallery/components/FourCut/index.tsx
  client/src/Gallery/components/FourCut/style.tsx
  client/src/Gallery/components/GalleryInfo/index.tsx
  client/src/Gallery/hooks/useLikeData.ts
  client/src/Gallery/hooks/useLikeData.tsx
  client/src/GallerySetting/GallerySetting.tsx
  client/src/GallerySetting/components/Input/index.tsx
  client/src/GallerySetting/galleryType.ts
  client/src/Intro/Redirect.tsx
  client/src/Intro/RedirectPage.tsx
  client/src/Intro/api.ts
  client/src/Intro/hooks/AutoRedirect.ts
  client/src/Intro/hooks/useUserData.ts
  client/src/shared/hooks/useAuth.tsx
  client/src/store/store.ts
  client/src/store/types.ts
Labels: FE, Feat, Style, Refactor

#151 [FEAT] RESTdocs 및 알림 기능 보완
  server/oneyearfourcut/src/docs/asciidoc/index.adoc
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/service/ArtworkLikeService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/controller/AlarmController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/proxy/Alarm.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/proxy/AlarmAction.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/proxy/AlarmActionInterceptor.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/resources/static/docs/index.html
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/AlarmControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkServiceTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/like/service/ArtworkLikeServiceTest.java
Labels: BE, Feat, Docs, Test

#153 [FE] Access token 재발행, refresh token 만료시 처리
  client/src/AlarmList/components/Alarm.tsx
  client/src/AlarmList/index.tsx
  client/src/AlarmList/types.ts
  client/src/App.tsx
  client/src/Intro/RedirectPage.tsx
  client/src/index.tsx
  client/src/shared/components/Header/index.tsx
  client/src/shared/components/Modal/api.tsx
  client/src/shared/components/Modal/components/ProfileModify.tsx
  client/src/shared/components/Modal/hooks/useModifyProfile.tsx
  client/src/shared/components/Toast/ToastData.tsx
  client/src/shared/components/Toast/components/ToastContainer.tsx
  client/src/shared/utils/axios.ts
Labels: FE, Feat, Refactor

#158 [FE]
  client/src/Gallery/GalleryAllPic.tsx
  client/src/Gallery/GalleryFourPic.tsx
  client/src/Gallery/components/DynamicGallery/index.tsx
  client/src/Gallery/components/DynamicGallery/style.tsx
  client/src/Gallery/components/GalleryInfo/index.tsx
  client/src/Intro/RedirectPage.tsx
  client/src/Intro/hooks/AutoRedirect.ts
  client/src/SinglePicture/index.tsx
  client/src/store/store.ts
Labels: FE, Feat, Refactor

#155 [Feat] 대댓글 알림 response 카테고리 추가
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/AlarmType.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/ReplyService.java
Labels: BE, Feat

#159 Fe inspection
  client/src/shared/components/Header/components/HeaderBox.tsx
  client/src/shared/components/Header/hook/useReceiveAlarm.tsx
  client/src/shared/components/Header/index.tsx
  client/src/shared/utils/axios.ts
Labels: FE, Refactor

#161 🚑FIX: 다른 사람 전시관 등록 시 그 전시관 작품 보이기
  client/src/Gallery/GalleryFourPic.tsx
  client/src/Gallery/components/ButtonBox/index.tsx
  client/src/Gallery/components/FourCut/index.tsx
  client/src/UploadPicture/index.tsx
  client/src/shared/components/Buttons/index.tsx
  client/src/shared/hooks/useAuth.tsx
Labels: FE, Fix

#163 [FE] 점검
  client/src/shared/components/Header/components/HeaderButtons.tsx
  client/src/shared/components/Header/hook/useReceiveAlarm.tsx
  client/src/shared/components/Header/index.tsx
  client/src/shared/components/Modal/hooks/useClipboardCopy.tsx
  client/src/shared/libs/uploadHelper.ts
Labels: FE, Fix

#168 🚑FIX: 버그 수정
  client/src/AlarmList/index.tsx
  client/src/ForBidden/index.tsx
  client/src/UploadPicture/index.tsx
  client/src/shared/components/Header/hook/useReceiveAlarm.tsx
  client/src/shared/components/Header/index.tsx
  client/src/shared/components/Modal/components/ModalContainer.ts
  client/src/shared/components/Toast/ToastData.tsx
  client/src/shared/styled/GlobalStyle.tsx
Labels: FE, Fix

#171 [FE #04,05,06] CSS 일부 수정, 오류 해결
  client/package-lock.json
  client/package.json
  client/src/AllComments/AllCommentInput.tsx
  client/src/AllComments/AllComments.tsx
  client/src/App.tsx
  client/src/SingleComments/CommentInput.tsx
  client/src/SingleComments/CommentsZone.tsx
  client/src/SingleComments/Single Comments.style.tsx
  client/src/SingleComments/SingleComment/SingleComment.style.tsx
  client/src/SingleComments/SingleComment/SingleComment.tsx
  client/src/SingleComments/index.tsx
  client/src/SinglePicture/OnePage/OnePicPage.tsx
  client/src/SinglePicture/SinglePage.style.tsx
  client/src/SinglePicture/SinglePicture.tsx
  client/src/SinglePicture/index.tsx
  client/src/SinglePicture/styles.css
  client/src/shared/components/Buttons/likeButton.tsx
  client/src/shared/components/PicFooter/PicFoot.style.tsx
Labels: FE, Fix, Style

#174 [FE #04,05,06]
  client/src/AllComments/AllCommentList.tsx
  client/src/SinglePicture/OnePage/OnePicPage.tsx
  client/src/SinglePicture/index.tsx
  client/src/shared/components/PicFooter/OpenComment.tsx
  client/src/shared/components/PicFooter/PicFooter.tsx
  client/src/store/store.ts
  client/src/store/types.ts
Labels: FE, Feat, Style

#175 이미지파일 형식변환
  client/package-lock.json
  client/package.json
  client/src/AlarmList/components/Alarm.tsx
  client/src/AlarmList/index.tsx
  client/src/UploadPicture/components/UploadImg.tsx
  client/src/shared/components/Header/components/HeaderBox.tsx
  client/src/shared/components/Header/index.tsx
  client/src/shared/components/Modal/components/ProfileModify.tsx
  client/src/shared/libs/uploadHelper.ts
Labels: FE, Feat

#176 멘토님 피드백 수정
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Gallery/components/BottonButton/index.tsx
  client/src/Gallery/components/ButtonBox/index.tsx
  client/src/Gallery/components/ButtonBox/style.tsx
  client/src/Gallery/components/DynamicGallery/index.tsx
  client/src/Gallery/components/DynamicGallery/style.tsx
  client/src/Gallery/components/FilterBox/index.tsx
  client/src/Gallery/components/FourCut/style.tsx
  client/src/Gallery/components/GalleryInfo/index.tsx
  client/src/Gallery/components/GalleryInfo/style.tsx
  client/src/Gallery/hooks/useLikeData.tsx
  client/src/GallerySetting/components/Input/index.tsx
  client/src/GallerySetting/components/Input/style.tsx
  client/src/Intro/RedirectPage.tsx
  client/src/shared/components/Buttons/index.tsx
  client/src/shared/components/Toast/ToastData.tsx
Labels: FE, Feat, Refactor

#169 [BE] 카카오 연결끊기 구현, test db 환경 분리
  .DS_Store
  server/.DS_Store
  server/oneyearfourcut/src/main/.DS_Store
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/service/MemberService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/RestTemplateConfig.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/SecurityConfig.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/handler/OAuth2MemberSuccessHandler.java
  server/oneyearfourcut/src/main/resources/application-real.yml
  server/oneyearfourcut/src/main/resources/static/docs/index.html
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberControllerRestDocsTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/refreshToken/controller/RefreshTokenControllerRestDocsTest.java
  server/oneyearfourcut/src/test/resources/application.yml
  server/oneyearfourcut/src/test/resources/db/testdata.sql
Labels: BE, Feat, Fix

#182 스타일, 버그수정
  client/src/AlarmList/components/AlarmContainer.ts
  client/src/AlarmList/index.tsx
  client/src/App.tsx
  client/src/Gallery/components/ButtonBox/index.tsx
  client/src/UploadPicture/hook/useUpload.tsx
  client/src/UploadPicture/index.tsx
  client/src/shared/components/Header/hook/useReceiveAlarm.tsx
  client/src/shared/components/Header/index.tsx
  client/src/shared/components/Modal/Alert.tsx
  client/src/shared/components/Modal/Profile.tsx
  client/src/shared/components/Modal/components/ModalBackdrop.tsx
  client/src/shared/components/Modal/hooks/useHandleService.tsx
  client/src/shared/components/Toast/ToastData.tsx
  client/src/shared/components/Toast/components/ToastContainer.tsx
  client/src/shared/components/Toast/components/ToastMessage.tsx
  client/src/shared/components/Toast/index.tsx
  client/src/shared/hooks/useNavigateSearch.tsx
  client/src/store/store.ts
  client/src/store/types.ts
Labels: FE, Style

#192 🚑FIX: 버그 수정
  client/src/AlarmList/index.tsx
  client/src/UploadPicture/components/Upload.tsx
  client/src/UploadPicture/components/UploadImg.tsx
  client/src/shared/components/Header/hook/useReceiveAlarm.tsx
Labels: FE, Fix

#188 [BE/#187] Artwork 응답 데이터 추가
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkResponseDto.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkControllerTest.java
  server/oneyearfourcut/src/test/resources/db/testdata.sql
Labels: BE, Refactor

#201 전시회 덧글 오류, 싱글 페이지 좋아요 및 이름 표시 , 삭제 범위 수정
  client/src/AllComments/AllCommentList.tsx
  client/src/AllComments/AllCommentOne.tsx
  client/src/SinglePicture/OnePage/OnePicPage.tsx
  client/src/SinglePicture/SinglePicture.tsx
  client/src/shared/components/Buttons/LikeBtn.tsx
  client/src/shared/components/Buttons/likeButton.tsx
  client/src/shared/hooks/useGetAllPost.tsx
Labels: FE, Fix, Style

#202 [FE] 업로드 페이지 로직변경
  client/src/AlarmList/components/Alarm.tsx
  client/src/AlarmList/types.ts
  client/src/SinglePicture/SinglePicture.tsx
  client/src/UploadPicture/api.ts
  client/src/UploadPicture/components/UploadImg.tsx
  client/src/UploadPicture/index.tsx
  client/src/UploadPicture/types.ts
  client/src/shared/components/Modal/Profile.tsx
  client/src/shared/components/Modal/components/ModalContainer.ts
  client/src/shared/components/Modal/components/ProfileModify.tsx
  client/src/shared/libs/uploadHelper.ts
  client/src/store/store.ts
  client/src/store/types.ts
Labels: FE, Feat

#203 사이트 소개 페이지 및 모아보기 수정
  client/src/Gallery/components/DynamicGallery/style.tsx
  client/src/Intro/Intro.tsx
  client/src/Intro/components/AIntro/index.tsx
  client/src/Intro/components/AIntro/style.tsx
  client/src/Intro/components/BIntro/style.tsx
  client/src/Intro/components/Demo/index.tsx
  client/src/Intro/components/Demo/style.tsx
  client/src/Intro/components/Envelope/index.tsx
  client/src/Intro/components/Envelope/style.tsx
  client/src/Intro/components/KakaoBtn/index.tsx
  client/src/Intro/components/Scroll/index.tsx
  client/src/Intro/components/Scroll/style.tsx
  client/src/shared/styled/Theme.ts
Labels: FE, Feat, Fix

#208 [FIX] 알림 galleryId response 수정
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
Labels: BE, Fix

#215 [BE] 댓글을 전시관 주인도 삭제, 수정할 수 있게 수정
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryControllerRestDocsTest.java
Labels: BE, Fix

#216 [BE/#187] 작품 삭제 시 관련 댓글 일괄 삭제
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/repository/ArtworkRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/repository/CommentRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkServiceTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryControllerRestDocsTest.java
Labels: BE, Refactor

#214 Fe final fix
  client/public/images/tree.png
  client/src/AllComments/AllCommentList.tsx
  client/src/AllComments/AllCommentOne.tsx
  client/src/SingleComments/CommentInput.tsx
  client/src/SinglePicture/SinglePicture.tsx
  client/src/shared/components/Buttons/likeButton.tsx
  client/src/shared/components/Modal/components/ModalContainer.ts
  client/src/shared/hooks/useDeleteSinglePic.tsx
Labels: FE, Fix, Style
